version: "3.8"

services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    networks:
      - nextcloud
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: change-me
      MYSQL_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - nextcloud
    command: redis-server --appendonly no

  nextcloud:
    image: nextcloud:27-apache
    restart: unless-stopped
    networks:
      - nextcloud
    depends_on:
      - db
      - redis
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      REDIS_HOST: redis
      NEXTCLOUD_TRUSTED_DOMAINS: cloud.example.com
    volumes:
      - nextcloud_html:/var/www/html

  # Uncomment the following service to run an Nginx reverse proxy in front of Nextcloud
  # nginx:
  #   image: nginx:alpine
  #   restart: unless-stopped
  #   networks:
  #     - nextcloud
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - nextcloud_html:/var/www/html:ro
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - nextcloud

networks:
  nextcloud:
    external: true

volumes:
  db:
  nextcloud_html:
